trigger: none  # só roda em PRs

pr:
  branches:
    include:
      - dev

pool:
  vmImage: ubuntu-latest

variables:
- name: NODE_VERSION
  value: '20.x'

stages:
  - stage: Build
    displayName: "SeedsUfcspa.Site-SEEDS (Build and Test Build Angular Application)"
    jobs:
      - job: SeedsUfcspa_BuildAndTest
        displayName: "SeedsUfcspa.Site-SEEDS (Build and Test Build Angular Application)"
        steps: 
          - task: NodeTool@0
            displayName: "Use Node.js $(NODE_VERSION)"
            inputs:
              versionSpec: $(NODE_VERSION)

          - script: npm ci
            displayName: "Install dependencies"
            workingDirectory: frontend

          - script: npm run build
            displayName: "Build application"
            workingDirectory: frontend
          
          - script: npm test -- --watch=false --browsers=ChromeHeadless
            displayName: "Run tests"
            workingDirectory: frontend

  - stage: Deploy
    displayName: "Deploy Application"
    dependsOn: Build
    condition: succeeded()
    jobs:
      - job: Deploy_to_Server
        displayName: "Deploy to Apache Server"
        steps:
          - download: none
          - task: CopyFiles@2
            displayName: "Copy files"
            inputs:
              SourceFolder: "frontend"
              Contents: "**"
              TargetFolder: "/var/www/seeds.ufcspa.edu.br/desenv/"
              CleanTargetFolder: true
          - task: Bash@3
            displayName: "pm2 config"
            inputs:
              targetType: inline
              script: |
                cd /var/www/seeds.ufcspa.edu.br/desenv/
                rm -rf node_modules/
                npm install --production
                pm2 reload seeds-ufcspa-desenv || pm2 start npm --name "seeds-ufcspa-desenv" -- run start-desenv
                pm2 save
